import { Image } from "../interfaces/Image"

export const IMAGES: Image[] = [
    {
        id: 0,
        title: "Squad Ghouls",
        description: "marker & pen",
        src: "images/squad_ghouls.png",
        orientation: "portrait",
        type: "illustration",
    },
    {
        id: 1,
        title: "Lightyears Davis",
        description: "marker & pen",
        src: "images/lightyears_davis.png",
        orientation: "portrait",
        type: "illustration",
    },
    {
        id: 2,
        title: "Beanie It's Cold Outside",
        description: "marker & pen",
        src: "images/beanie_it's_cold_outside.png",
        orientation: "portrait",
        type: "illustration",
    },
    {
        id: 3,
        title: "Duckie",
        description: "marker & pen",
        src: "images/duckie.png",
        orientation: "landscape",
        type: "illustration",
    },
    {
        id: 4,
        title: "Eat Your Vegetables",
        description: "marker & pen",
        src: "images/eat_your_vegetables.png",
        orientation: "portrait",
        type: "illustration",
    },
    {
        id: 5,
        title: "Grapes",
        description: "marker & pen",
        src: "images/grapes.png",
        orientation: "portrait",
        type: "illustration",
    },
    {
        id: 6,
        title: "It's Just a Plant",
        description: "marker & pen",
        src: "images/it's_just_a_plant.png",
        orientation: "portrait",
        type: "illustration",
    },
    {
        id: 7,
        title: "Swab the Duck",
        description: "marker & pen",
        src: "images/swab_the_duck.png",
        orientation: "portrait",
        type: "illustration",
    },
    {
        id: 8,
        title: "Milk",
        description: "marker & pen",
        src: "images/milk.png",
        orientation: "portrait",
        type: "illustration",
    },
    {
        id: 9,
        title: "Definitely a Gerald",
        description: "marker & pen",
        src: "images/definitely_a_gerald.png",
        orientation: "portrait",
        type: "illustration",
    },
    {
        id: 10,
        title: "Ohhhh a Baby!",
        description: "marker & pen",
        src: "images/ohhhh_ababy.png",
        orientation: "landscape",
        type: "illustration",
    },
    {
        id: 11,
        title: "Holdin' Delicious",
        description: "marker & pen",
        src: "images/holdin_delicious.png",
        orientation: "portrait",
        type: "illustration",
    },
    {
        id: 12,
        title: "I Feel Ya",
        description: "marker & pen",
        src: "images/i_feel_ya.png",
        orientation: "landscape",
        type: "illustration",
    },
    {
        id: 13,
        title: "Henry",
        description: "marker & pen",
        src: "images/henry.png",
        orientation: "portrait",
        type: "illustration",
    },
    {
        id: 14,
        title: "Apple",
        description: "marker & pen",
        src: "images/apple.png",
        orientation: "square",
        type: "illustration",
    },
    {
        id: 15,
        title: "Pokey LaFarge",
        description: "acrylic",
        src: "images/pokey.png",
        orientation: "portrait",
        type: "painting",
    },
    {
        id: 16,
        title: "Charles Bradley",
        description: "acrylic & charcoal",
        src: "images/charles_bradley.png",
        orientation: "square",
        type: "painting",
    },
    {
        id: 17,
        title: "Molly",
        description: "acrylic & marker",
        src: "images/molly.png",
        orientation: "landscape",
        type: "painting",
    },
]